export let beautyArr = [{id:1, thumbnailImg:"https://m.media-amazon.com/images/I/713DeNFZKwL._AC_SY200_.jpg"},
{id:2, thumbnailImg:"https://m.media-amazon.com/images/I/71DT0w9olZL._AC_SY200_.jpg"},
{id:3, thumbnailImg:"https://m.media-amazon.com/images/I/716aAlijGdL._AC_SY200_.jpg"},
{id:4, thumbnailImg:"https://m.media-amazon.com/images/I/61IGfI1aq3L._AC_SY200_.jpg"},
{id:5, thumbnailImg:"https://m.media-amazon.com/images/I/61uNVxIpgyL._AC_SY200_.jpg"},
{id:6, thumbnailImg:"https://m.media-amazon.com/images/I/61iZN6WxhxL._AC_SY200_.jpg"},
{id:7, thumbnailImg:"https://m.media-amazon.com/images/I/61fhtZytAwL._AC_SY200_.jpg"},
{id:8, thumbnailImg:"https://m.media-amazon.com/images/I/71bp3Fp7xLL._AC_SY200_.jpg"},
{id:9, thumbnailImg:"https://m.media-amazon.com/images/I/71vx-9iCENL._AC_SY200_.jpg"},
{id:10, thumbnailImg:"https://m.media-amazon.com/images/I/718jjwHXq8L._AC_SY200_.jpg"},
{id:11, thumbnailImg:"https://m.media-amazon.com/images/I/71KFzsxS++L._AC_SY200_.jpg"},
{id:12, thumbnailImg:"https://m.media-amazon.com/images/I/71orkcA2mGL._AC_SY200_.jpg"},
{id:13, thumbnailImg:"https://m.media-amazon.com/images/I/71o1Q0jxUbL._AC_SY200_.jpg"},
{id:14, thumbnailImg:"https://m.media-amazon.com/images/I/61du-rzEoTL._AC_SY200_.jpg"},
{id:15, thumbnailImg:"https://m.media-amazon.com/images/I/71eRSX8IqtL._AC_SY200_.jpg"},
]