export let todaysDealsArr = [{id:1, offPercentage: "19% off", price:"$64", name:"Amazon Fire TV Stick 4K Max streamin...", thumbnailImg:"https://m.media-amazon.com/images/I/51L1wL2UlnL._AC_SY300_SX300_.jpg"},
{id:2, offPercentage: "15% off", price:"$289", name:"Amazon Fire TV 40 2-Series HD smart...", thumbnailImg: "https://m.media-amazon.com/images/I/71tUde29hbL._AC_SY300_SX300_.jpg"},
{id:3, offPercentage: "20% off", price:"$239", name:"DJI Mini 3 Fly More Combo (DJI RC) ,Li…", thumbnailImg:"https://m.media-amazon.com/images/I/61FWZ4fHrkL._AC_SY355_.jpg"},
{id:4, offPercentage: "38% off", price:"$279", name:"Samsung Galaxy S6 Lite (2024) - Gray…", thumbnailImg:"https://m.media-amazon.com/images/I/61vsK7h3zVL._AC_SX355_.jpg"},
{id:5, offPercentage: "22% off", price:"$350", name:"Serene Life Portable Electric Air Condi…", thumbnailImg:"https://m.media-amazon.com/images/I/41p24zbVsNL._SR480,440_.jpg"},
{id:6, offPercentage: "38% off", price:"$117", name:"Keurig K-Supreme Single Serve K-Cup…", thumbnailImg: "https://m.media-amazon.com/images/I/31ijGiDj+mL._SR480,440_.jpg"},
{id:7, offPercentage: "19% off", price:"$1,207", name:"ASUS TUF Gaming A17 (2024) Gaming…", thumbnailImg:"https://m.media-amazon.com/images/I/51VGacxVwXL._SR480,440_.jpg"},
{id:8, offPercentage: "26% off", price:"$296", name:"Skatinger 11 6 35 Super Wide Inflata…", thumbnailImg:"https://m.media-amazon.com/images/I/51PwUXLFxDL._SR480,440_.jpg"},
{id:9, offPercentage: "42% off", price:"$719", name:"ARCCAPTAIN TIG Welder AC/DC 200A…", thumbnailImg:"https://m.media-amazon.com/images/I/51Dtix6tniL._SR480,440_.jpg"},
{id:10, offPercentage: "11% off", price:"$159", name:"Queen Mattress, Molblly 12 Inch Mate…", thumbnailImg: "https://m.media-amazon.com/images/I/51KorlIae6L._SR480,440_.jpg"},
{id:11, offPercentage: "41% off", price:"$998", name:"Samsung 49 Odyssey G9 Gaming Mo…", thumbnailImg: "https://m.media-amazon.com/images/I/41k0HI-1LKL._SR480,440_.jpg"},
{id:12, offPercentage: "14% off", price:"$179", name:"FDW Wicker Patio Furniture 4 Piece Pa…", thumbnailImg: "https://m.media-amazon.com/images/I/41TB1O7jUJL._SR480,440_.jpg"},
{id:13, offPercentage: "23% off", price:"$229", name:"Sperax Walking Pad, Under Desk Trea…", thumbnailImg: "https://m.media-amazon.com/images/I/41GGfI9hzKL._SR480,440_.jpg"},
];