export let toysGamesArr = [{id:1, thumbnailImg:"https://m.media-amazon.com/images/I/71vQi-auFOL._AC_SY200_.jpg"},
{id:2, thumbnailImg:"https://m.media-amazon.com/images/I/81kTVgT-W5L._AC_SY200_.jpg"},
{id:3, thumbnailImg:"https://m.media-amazon.com/images/I/51uZjEMxWTS._AC_SY200_.jpg"},
{id:4, thumbnailImg:"https://m.media-amazon.com/images/I/71RS4M0qQGL._AC_SY200_.jpg"},
{id:5, thumbnailImg:"https://m.media-amazon.com/images/I/614ngmgsIcL._AC_SY200_.jpg"},
{id:6, thumbnailImg:"https://m.media-amazon.com/images/I/81QQOmhZwOL._AC_SY200_.jpg"},
{id:7, thumbnailImg:"https://m.media-amazon.com/images/I/81J9V3mm8PL._AC_SY200_.jpg"},
{id:8, thumbnailImg:"https://m.media-amazon.com/images/I/71eJNnl+TQL._AC_SY200_.jpg"},
{id:9, thumbnailImg:"https://m.media-amazon.com/images/I/81OcKm1MXQL._AC_SY200_.jpg"},
{id:10, thumbnailImg:"https://m.media-amazon.com/images/I/81A+5FYgfDL._AC_SY200_.jpg"},
{id:11, thumbnailImg:"https://m.media-amazon.com/images/I/81P8W3UH6nL._AC_SY200_.jpg"},
{id:12, thumbnailImg:"https://m.media-amazon.com/images/I/81W0FmilsvL._AC_SY200_.jpg"},
{id:13, thumbnailImg:"https://m.media-amazon.com/images/I/71hV4BKbAJL._AC_SY200_.jpg"},
{id:14, thumbnailImg:"https://m.media-amazon.com/images/I/81WWAnTwaBL._AC_SY200_.jpg"},
{id:15, thumbnailImg:"https://m.media-amazon.com/images/I/810wzzp13+L._AC_SY200_.jpg"},
]